name: CI/CD

on:
  push: #pull:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{github.run_id}}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/nodejs-app/values.yaml
      


      - name: Commit and push changes
        run: |
          git config --global user.email "saijathin51@gmail.com"
          git config --global user.name "sai jathin"
          git add helm/nodejs-app/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
    # - name: Notify Slack
    #   uses: rtCamp/action-slack-notify@v2
    #   with:
      #     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     status: ${{ job.status }}
